// Job Board Data
// Structure ready for API/scraping integration
// Currently using mock data for demo

export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  description: string;
  requirements: string[];
  payMin: number;
  payMax: number;
  payType: "hourly" | "salary";
  hoursType: "full-time" | "part-time" | "contract" | "temporary";
  hoursPerWeek?: number;
  datePosted: string;
  source: "worksourcewa" | "indeed" | "linkedin" | "governmentjobs";
  sourceUrl: string;
  category: "healthcare" | "manufacturing" | "admin" | "retail" | "tech" | "other";
  remote: boolean;
  benefits?: string[];
  companyLogo?: string;
}

export interface JobApplication {
  id: string;
  jobId: string;
  job: Job;
  status: "applied" | "phone-screen" | "first-interview" | "final-interview" | "offered" | "hired" | "rejected";
  appliedDate: string;
  lastUpdated: string;
  notes?: string;
  // Hired outcome data
  hiredData?: {
    startDate: string;
    jobTitle: string;
    hourlyWage?: number;
    salary?: number;
    hoursPerWeek: number;
    successStory?: string;
  };
}

// Job status stages with colors (stoplight system)
export const jobStatuses = [
  { id: "applied", label: "Applied", color: "#3B82F6", bgColor: "bg-blue-100", textColor: "text-blue-700" },
  { id: "phone-screen", label: "Phone Screen", color: "#8B5CF6", bgColor: "bg-purple-100", textColor: "text-purple-700" },
  { id: "first-interview", label: "1st Interview", color: "#F59E0B", bgColor: "bg-yellow-100", textColor: "text-yellow-700" },
  { id: "final-interview", label: "Final Interview", color: "#F97316", bgColor: "bg-orange-100", textColor: "text-orange-700" },
  { id: "offered", label: "Offered", color: "#10B981", bgColor: "bg-emerald-100", textColor: "text-emerald-700" },
  { id: "hired", label: "Hired", color: "#22C55E", bgColor: "bg-green-100", textColor: "text-green-700" },
  { id: "rejected", label: "Rejected", color: "#EF4444", bgColor: "bg-red-100", textColor: "text-red-700" },
];

// Helper to generate dates
const daysAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Mock Jobs Data - 50+ jobs across categories
export const mockJobs: Job[] = [
  // HEALTHCARE (15 jobs)
  {
    id: "job-h1",
    title: "Certified Nursing Assistant (CNA)",
    company: "Providence Health",
    location: "Spokane, WA",
    description: "Join our compassionate care team as a CNA. Provide direct patient care, assist with daily living activities, and support nursing staff in delivering exceptional healthcare.",
    requirements: ["Current CNA certification in WA", "BLS certification", "1+ year experience preferred", "Ability to lift 50+ lbs"],
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/cna-providence",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "PTO", "Tuition Reimbursement"],
  },
  {
    id: "job-h2",
    title: "Medical Receptionist",
    company: "MultiCare Health System",
    location: "Spokane Valley, WA",
    description: "Front desk position handling patient check-in, scheduling, insurance verification, and general administrative duties in a busy medical clinic.",
    requirements: ["High school diploma", "1+ year medical office experience", "Knowledge of medical terminology", "Strong customer service skills"],
    payMin: 17,
    payMax: 21,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/medical-receptionist-multicare",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental", "PTO", "Employee Assistance Program"],
  },
  {
    id: "job-h3",
    title: "Home Health Aide",
    company: "Comfort Keepers",
    location: "Spokane, WA",
    description: "Provide in-home care to elderly and disabled clients. Duties include personal care, meal preparation, light housekeeping, and companionship.",
    requirements: ["NAC certification preferred", "Valid driver's license", "Reliable transportation", "Pass background check"],
    payMin: 16,
    payMax: 19,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 25,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/home-health-aide",
    category: "healthcare",
    remote: false,
  },
  {
    id: "job-h4",
    title: "Pharmacy Technician",
    company: "Walgreens",
    location: "Spokane, WA",
    description: "Assist pharmacists in preparing and dispensing medications. Handle customer service, inventory management, and prescription processing.",
    requirements: ["Pharmacy Technician certification", "Retail experience preferred", "Attention to detail", "Customer service skills"],
    payMin: 17,
    payMax: 22,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/pharmacy-tech-walgreens",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Employee discount"],
  },
  {
    id: "job-h5",
    title: "Physical Therapy Assistant",
    company: "Spokane PT & Sports Medicine",
    location: "Spokane, WA",
    description: "Work alongside licensed physical therapists to help patients recover from injuries and improve mobility through therapeutic exercises.",
    requirements: ["Associate degree in PTA", "WA PTA license", "CPR certified", "Strong interpersonal skills"],
    payMin: 25,
    payMax: 32,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(5),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/pta-spokane",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "CEU allowance", "PTO"],
  },
  {
    id: "job-h6",
    title: "Medical Billing Specialist",
    company: "Inland Imaging",
    location: "Spokane, WA",
    description: "Process medical claims, verify insurance coverage, follow up on unpaid claims, and handle patient billing inquiries.",
    requirements: ["Medical billing certification preferred", "2+ years billing experience", "Knowledge of ICD-10 and CPT codes", "Epic experience a plus"],
    payMin: 20,
    payMax: 26,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/medical-billing",
    category: "healthcare",
    remote: true,
    benefits: ["Medical/Dental/Vision", "Remote work", "401k"],
  },
  {
    id: "job-h7",
    title: "Dental Hygienist",
    company: "Spokane Family Dentistry",
    location: "Spokane, WA",
    description: "Perform dental cleanings, take x-rays, educate patients on oral health, and assist dentists with procedures.",
    requirements: ["Associate degree in Dental Hygiene", "WA Dental Hygienist license", "CPR certified", "1+ year experience"],
    payMin: 40,
    payMax: 55,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 36,
    datePosted: daysAgo(4),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/dental-hygienist-spokane",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental", "401k", "CE reimbursement"],
  },
  {
    id: "job-h8",
    title: "Emergency Medical Technician (EMT)",
    company: "AMR",
    location: "Spokane, WA",
    description: "Respond to emergency calls, provide pre-hospital care, transport patients, and work as part of an ambulance crew.",
    requirements: ["Current WA EMT certification", "Valid driver's license", "CPR/BLS certified", "Physical fitness requirements"],
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "governmentjobs",
    sourceUrl: "https://governmentjobs.com/emt-spokane",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Paid training"],
  },
  {
    id: "job-h9",
    title: "Mental Health Technician",
    company: "Frontier Behavioral Health",
    location: "Spokane, WA",
    description: "Support individuals with mental health challenges in residential or outpatient settings. Monitor patients, lead group activities, and document progress.",
    requirements: ["Bachelor's in Psychology preferred", "Experience with mental health population", "Crisis intervention training", "Valid driver's license"],
    payMin: 19,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(6),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/mental-health-tech",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "EAP", "Student loan assistance"],
  },
  {
    id: "job-h10",
    title: "Phlebotomist",
    company: "LabCorp",
    location: "Spokane, WA",
    description: "Draw blood samples from patients, process specimens, maintain equipment, and ensure patient comfort during procedures.",
    requirements: ["Phlebotomy certification", "1+ year experience", "Customer service skills", "Attention to detail"],
    payMin: 17,
    payMax: 21,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/phlebotomist-labcorp",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "PTO"],
  },
  {
    id: "job-h11",
    title: "Medical Assistant",
    company: "CHAS Health",
    location: "Spokane, WA",
    description: "Support physicians with patient care, take vitals, administer injections, assist with procedures, and manage patient records.",
    requirements: ["Medical Assistant certification", "EHR experience", "CPR certified", "Bilingual Spanish a plus"],
    payMin: 18,
    payMax: 23,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/medical-assistant-chas",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Loan repayment program"],
  },
  {
    id: "job-h12",
    title: "Radiologic Technologist",
    company: "Sacred Heart Medical Center",
    location: "Spokane, WA",
    description: "Operate X-ray and imaging equipment, position patients, ensure image quality, and maintain radiation safety protocols.",
    requirements: ["Associate degree in Radiologic Technology", "ARRT certification", "WA State license", "BLS certified"],
    payMin: 30,
    payMax: 42,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(7),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/rad-tech-sacred-heart",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Tuition assistance"],
  },
  {
    id: "job-h13",
    title: "Occupational Therapy Assistant",
    company: "Kindred RehabCare",
    location: "Spokane, WA",
    description: "Assist occupational therapists in helping patients develop, recover, and improve skills needed for daily living and working.",
    requirements: ["Associate degree in OTA", "WA OTA license", "Experience with elderly population preferred", "Strong communication skills"],
    payMin: 26,
    payMax: 34,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/ota-kindred",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "CEU allowance", "401k"],
  },
  {
    id: "job-h14",
    title: "Sterile Processing Technician",
    company: "Deaconess Hospital",
    location: "Spokane, WA",
    description: "Clean, sterilize, and prepare surgical instruments and equipment. Maintain inventory and ensure compliance with infection control standards.",
    requirements: ["High school diploma", "SPD certification preferred", "Attention to detail", "Ability to stand for long periods"],
    payMin: 17,
    payMax: 22,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/sterile-processing",
    category: "healthcare",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Shift differential", "Tuition reimbursement"],
  },
  {
    id: "job-h15",
    title: "Healthcare Customer Service Rep",
    company: "Premera Blue Cross",
    location: "Spokane, WA",
    description: "Handle member inquiries about health insurance coverage, claims, and benefits. Resolve issues and provide excellent customer service.",
    requirements: ["High school diploma", "1+ year customer service experience", "Healthcare knowledge preferred", "Strong computer skills"],
    payMin: 18,
    payMax: 23,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/csr-premera",
    category: "healthcare",
    remote: true,
    benefits: ["Medical/Dental/Vision", "Work from home", "401k match"],
  },

  // MANUFACTURING (12 jobs)
  {
    id: "job-m1",
    title: "Production Assembler",
    company: "Schweitzer Engineering Laboratories",
    location: "Pullman, WA",
    description: "Assemble electronic components and products according to specifications. Perform quality checks and maintain production records.",
    requirements: ["High school diploma", "Manual dexterity", "Ability to read schematics", "Attention to detail"],
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/production-assembler",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Profit sharing"],
  },
  {
    id: "job-m2",
    title: "CNC Machine Operator",
    company: "Spokane Industries",
    location: "Spokane, WA",
    description: "Set up and operate CNC machines to produce precision parts. Read blueprints, perform quality inspections, and maintain equipment.",
    requirements: ["CNC experience required", "Blueprint reading", "Basic math skills", "Quality control knowledge"],
    payMin: 22,
    payMax: 30,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/cnc-operator-spokane",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Overtime available", "Tool allowance"],
  },
  {
    id: "job-m3",
    title: "Warehouse Associate",
    company: "Amazon Fulfillment Center",
    location: "Spokane, WA",
    description: "Pick, pack, and ship customer orders. Operate RF scanners, maintain organization, and meet productivity goals.",
    requirements: ["Ability to lift 50 lbs", "Stand/walk for 10+ hours", "Basic computer skills", "Reliable attendance"],
    payMin: 18,
    payMax: 21,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/warehouse-amazon-spokane",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical from day 1", "401k", "Career advancement"],
  },
  {
    id: "job-m4",
    title: "Welder - MIG/TIG",
    company: "Pearson Packaging Systems",
    location: "Spokane, WA",
    description: "Perform MIG and TIG welding on steel and aluminum. Read blueprints, set up fixtures, and ensure quality standards.",
    requirements: ["Welding certification", "3+ years experience", "Blueprint reading", "Safety conscious"],
    payMin: 24,
    payMax: 32,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(5),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/welder-pearson",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Paid holidays"],
  },
  {
    id: "job-m5",
    title: "Forklift Operator",
    company: "UPS Supply Chain Solutions",
    location: "Spokane, WA",
    description: "Operate forklifts to move, load, and unload materials. Maintain inventory accuracy and follow safety procedures.",
    requirements: ["Valid forklift certification", "Warehouse experience", "Physical stamina", "Team player"],
    payMin: 19,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/forklift-ups-spokane",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Union benefits"],
  },
  {
    id: "job-m6",
    title: "Quality Control Inspector",
    company: "Triumph Composite Systems",
    location: "Spokane, WA",
    description: "Inspect aerospace components for defects and compliance. Document findings, use precision measuring tools, and maintain quality records.",
    requirements: ["High school diploma", "QC experience preferred", "Attention to detail", "Blueprint reading"],
    payMin: 20,
    payMax: 28,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/qc-inspector-triumph",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Tuition reimbursement"],
  },
  {
    id: "job-m7",
    title: "Maintenance Technician",
    company: "Packaging Corporation of America",
    location: "Spokane, WA",
    description: "Perform preventive and corrective maintenance on manufacturing equipment. Troubleshoot electrical and mechanical issues.",
    requirements: ["Maintenance experience", "Electrical/mechanical skills", "Ability to read schematics", "Problem-solving skills"],
    payMin: 25,
    payMax: 35,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/maintenance-tech-pca",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Overtime available"],
  },
  {
    id: "job-m8",
    title: "Production Supervisor",
    company: "Darigold",
    location: "Spokane, WA",
    description: "Supervise production team, ensure quality and safety standards, manage schedules, and drive continuous improvement initiatives.",
    requirements: ["3+ years manufacturing experience", "Supervisory experience", "Food safety knowledge", "Leadership skills"],
    payMin: 60000,
    payMax: 75000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 45,
    datePosted: daysAgo(6),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/production-supervisor-darigold",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Bonus potential"],
  },
  {
    id: "job-m9",
    title: "Machine Operator - Entry Level",
    company: "Inland Empire Paper",
    location: "Spokane, WA",
    description: "Operate paper manufacturing machinery. Monitor production, make adjustments, and perform basic maintenance.",
    requirements: ["High school diploma", "Mechanical aptitude", "Ability to work rotating shifts", "Reliable transportation"],
    payMin: 19,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/machine-operator-iep",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Union membership"],
  },
  {
    id: "job-m10",
    title: "Shipping & Receiving Clerk",
    company: "Costco Wholesale",
    location: "Spokane, WA",
    description: "Receive incoming shipments, verify orders, organize inventory, and prepare outgoing shipments. Maintain accurate records.",
    requirements: ["Warehouse experience", "Computer skills", "Forklift experience a plus", "Organizational skills"],
    payMin: 18,
    payMax: 23,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/shipping-receiving-costco",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Employee discount"],
  },
  {
    id: "job-m11",
    title: "Industrial Painter",
    company: "Metal Fabrication Inc",
    location: "Spokane Valley, WA",
    description: "Apply industrial coatings to metal products using spray equipment. Prepare surfaces, mix paints, and maintain quality standards.",
    requirements: ["Painting experience", "Knowledge of coating systems", "Attention to detail", "Safety conscious"],
    payMin: 20,
    payMax: 26,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/industrial-painter",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental", "401k", "Safety bonuses"],
  },
  {
    id: "job-m12",
    title: "Electrical Assembler",
    company: "Itron Inc",
    location: "Spokane, WA",
    description: "Assemble electrical components for utility meters. Solder, wire, and test assemblies according to specifications.",
    requirements: ["Electronics assembly experience", "Soldering skills", "Ability to read schematics", "Quality focused"],
    payMin: 19,
    payMax: 25,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/electrical-assembler-itron",
    category: "manufacturing",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Stock options"],
  },

  // ADMIN (12 jobs)
  {
    id: "job-a1",
    title: "Administrative Assistant",
    company: "Spokane County",
    location: "Spokane, WA",
    description: "Provide administrative support to county departments. Handle correspondence, scheduling, data entry, and customer service.",
    requirements: ["High school diploma", "2+ years admin experience", "Microsoft Office proficiency", "Excellent communication"],
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "governmentjobs",
    sourceUrl: "https://governmentjobs.com/admin-assistant-spokane-county",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Generous PTO"],
  },
  {
    id: "job-a2",
    title: "Receptionist",
    company: "Witherspoon Kelley Attorneys",
    location: "Spokane, WA",
    description: "Greet clients, answer phones, manage schedules, and provide general office support for a busy law firm.",
    requirements: ["Professional demeanor", "Multi-line phone experience", "Organizational skills", "Confidentiality"],
    payMin: 16,
    payMax: 20,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/receptionist-witherspoon",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental", "401k", "Parking provided"],
  },
  {
    id: "job-a3",
    title: "Data Entry Clerk",
    company: "Numerica Credit Union",
    location: "Spokane, WA",
    description: "Enter and verify financial data, process documents, and maintain accurate records in banking systems.",
    requirements: ["Data entry experience", "Attention to detail", "10-key proficiency", "Banking experience a plus"],
    payMin: 17,
    payMax: 21,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/data-entry-numerica",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Free checking"],
  },
  {
    id: "job-a4",
    title: "Office Manager",
    company: "Spokane Spine Center",
    location: "Spokane, WA",
    description: "Oversee daily office operations, manage staff, handle billing, and ensure excellent patient experience.",
    requirements: ["3+ years office management", "Healthcare experience preferred", "Leadership skills", "Problem-solving ability"],
    payMin: 50000,
    payMax: 62000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(5),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/office-manager-spine-center",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "PTO"],
  },
  {
    id: "job-a5",
    title: "Executive Assistant",
    company: "Avista Corporation",
    location: "Spokane, WA",
    description: "Support C-level executives with calendar management, travel arrangements, meeting coordination, and confidential projects.",
    requirements: ["5+ years executive support", "Advanced MS Office", "Discretion with sensitive info", "Excellent writing skills"],
    payMin: 55000,
    payMax: 70000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/executive-assistant-avista",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Tuition reimbursement"],
  },
  {
    id: "job-a6",
    title: "Human Resources Coordinator",
    company: "Spokane Public Schools",
    location: "Spokane, WA",
    description: "Support HR functions including recruitment, onboarding, benefits administration, and employee records management.",
    requirements: ["Bachelor's in HR or related", "1+ year HR experience", "HRIS experience", "Knowledge of employment law"],
    payMin: 45000,
    payMax: 55000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "governmentjobs",
    sourceUrl: "https://governmentjobs.com/hr-coordinator-sps",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pension", "Summer schedule"],
  },
  {
    id: "job-a7",
    title: "Accounts Payable Clerk",
    company: "Cowles Company",
    location: "Spokane, WA",
    description: "Process invoices, reconcile vendor accounts, prepare payments, and maintain accurate financial records.",
    requirements: ["AP experience", "Accounting knowledge", "Excel proficiency", "Detail-oriented"],
    payMin: 20,
    payMax: 26,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(1),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/ap-clerk-cowles",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Newspaper subscription"],
  },
  {
    id: "job-a8",
    title: "Legal Secretary",
    company: "Lukins & Annis PS",
    location: "Spokane, WA",
    description: "Provide secretarial support to attorneys. Prepare legal documents, manage files, schedule depositions, and client communication.",
    requirements: ["Legal secretary experience", "Legal terminology knowledge", "Typing 60+ WPM", "E-filing experience"],
    payMin: 22,
    payMax: 30,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(6),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/legal-secretary-lukins",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Paid parking"],
  },
  {
    id: "job-a9",
    title: "Customer Service Representative",
    company: "STCU",
    location: "Spokane, WA",
    description: "Assist members with banking needs via phone and in-person. Process transactions, resolve issues, and promote products.",
    requirements: ["Customer service experience", "Cash handling", "Sales aptitude", "Positive attitude"],
    payMin: 17,
    payMax: 22,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/csr-stcu",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k match", "Profit sharing"],
  },
  {
    id: "job-a10",
    title: "Payroll Specialist",
    company: "Gonzaga University",
    location: "Spokane, WA",
    description: "Process bi-weekly payroll, maintain employee records, handle tax filings, and respond to payroll inquiries.",
    requirements: ["Payroll experience", "ADP or similar system", "Knowledge of payroll regulations", "Accuracy focused"],
    payMin: 48000,
    payMax: 58000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(2),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/payroll-specialist-gonzaga",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Retirement", "Tuition benefits"],
  },
  {
    id: "job-a11",
    title: "Insurance Claims Processor",
    company: "Premera Blue Cross",
    location: "Spokane, WA",
    description: "Review and process health insurance claims. Verify coverage, apply benefits, and ensure accurate payment.",
    requirements: ["Claims processing experience", "Medical coding knowledge", "Attention to detail", "Computer proficiency"],
    payMin: 19,
    payMax: 25,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/claims-processor-premera",
    category: "admin",
    remote: true,
    benefits: ["Medical/Dental/Vision", "Work from home", "401k"],
  },
  {
    id: "job-a12",
    title: "Project Coordinator",
    company: "Garco Construction",
    location: "Spokane, WA",
    description: "Support project managers with scheduling, documentation, permits, and coordination between teams and subcontractors.",
    requirements: ["Construction industry experience", "Project coordination skills", "MS Project or similar", "Communication skills"],
    payMin: 50000,
    payMax: 62000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/project-coordinator-garco",
    category: "admin",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Vehicle allowance"],
  },

  // RETAIL (13 jobs)
  {
    id: "job-r1",
    title: "Sales Associate",
    company: "REI",
    location: "Spokane, WA",
    description: "Help customers find outdoor gear, share product knowledge, process transactions, and maintain store displays.",
    requirements: ["Retail experience", "Outdoor recreation passion", "Customer service skills", "Flexible availability"],
    payMin: 16,
    payMax: 20,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 25,
    datePosted: daysAgo(1),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/sales-associate-rei",
    category: "retail",
    remote: false,
    benefits: ["Employee discount", "Gear loaner program", "Pro deals"],
  },
  {
    id: "job-r2",
    title: "Cashier",
    company: "Safeway",
    location: "Spokane, WA",
    description: "Process customer purchases, handle cash and card transactions, bag groceries, and provide friendly customer service.",
    requirements: ["Cash handling experience", "Customer service", "Standing for long periods", "Basic math skills"],
    payMin: 16,
    payMax: 18,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 20,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/cashier-safeway",
    category: "retail",
    remote: false,
    benefits: ["Union benefits", "Employee discount", "Flexible hours"],
  },
  {
    id: "job-r3",
    title: "Store Manager",
    company: "Dollar Tree",
    location: "Spokane, WA",
    description: "Lead store operations, manage team, control inventory, ensure customer satisfaction, and drive sales performance.",
    requirements: ["Retail management experience", "Leadership skills", "Inventory management", "P&L responsibility"],
    payMin: 45000,
    payMax: 55000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 45,
    datePosted: daysAgo(2),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/store-manager-dollar-tree",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Bonus potential"],
  },
  {
    id: "job-r4",
    title: "Barista",
    company: "Starbucks",
    location: "Spokane, WA",
    description: "Craft handmade beverages, provide excellent customer service, maintain cleanliness, and work as part of a team.",
    requirements: ["Customer service experience", "Ability to work quickly", "Team player", "Morning/evening availability"],
    payMin: 16,
    payMax: 19,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 25,
    datePosted: daysAgo(1),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/barista-starbucks-spokane",
    category: "retail",
    remote: false,
    benefits: ["Free coffee", "Health insurance (20+ hrs)", "Stock grants"],
  },
  {
    id: "job-r5",
    title: "Inventory Specialist",
    company: "Target",
    location: "Spokane, WA",
    description: "Manage store inventory, process shipments, ensure accurate counts, and maintain backroom organization.",
    requirements: ["Inventory experience", "Physical stamina", "Early morning availability", "RF scanner experience"],
    payMin: 17,
    payMax: 21,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/inventory-specialist-target",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Employee discount"],
  },
  {
    id: "job-r6",
    title: "Assistant Store Manager",
    company: "Petco",
    location: "Spokane, WA",
    description: "Support store manager with operations, lead sales team, ensure animal care standards, and deliver excellent customer experience.",
    requirements: ["Retail experience", "Leadership skills", "Animal care knowledge", "Sales driven"],
    payMin: 40000,
    payMax: 48000,
    payType: "salary",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(4),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/asm-petco",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Pet adoption discount", "401k"],
  },
  {
    id: "job-r7",
    title: "Electronics Sales Specialist",
    company: "Best Buy",
    location: "Spokane, WA",
    description: "Help customers find technology solutions, demonstrate products, and provide expert advice on electronics.",
    requirements: ["Tech knowledge", "Sales experience", "Communication skills", "Customer focused"],
    payMin: 17,
    payMax: 22,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(0),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/electronics-sales-bestbuy",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental", "Employee discount", "Commission"],
  },
  {
    id: "job-r8",
    title: "Pharmacy Sales Associate",
    company: "Rite Aid",
    location: "Spokane, WA",
    description: "Assist customers, stock shelves, operate register, and support pharmacy operations in a retail drugstore.",
    requirements: ["Retail experience", "Customer service", "Flexibility", "Reliable attendance"],
    payMin: 15,
    payMax: 18,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 20,
    datePosted: daysAgo(2),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/sales-associate-riteaid",
    category: "retail",
    remote: false,
    benefits: ["Employee discount", "Flexible schedule"],
  },
  {
    id: "job-r9",
    title: "Visual Merchandiser",
    company: "Nordstrom",
    location: "Spokane, WA",
    description: "Create compelling product displays, maintain visual standards, and support sales through effective merchandising.",
    requirements: ["Visual merchandising experience", "Fashion sense", "Creativity", "Physical ability to set displays"],
    payMin: 18,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(5),
    source: "linkedin",
    sourceUrl: "https://linkedin.com/jobs/visual-merchandiser-nordstrom",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental/Vision", "Employee discount", "401k"],
  },
  {
    id: "job-r10",
    title: "Deli Clerk",
    company: "Yokes Fresh Market",
    location: "Spokane, WA",
    description: "Prepare and serve deli items, maintain food safety standards, assist customers, and keep deli area clean.",
    requirements: ["Food service experience", "Food handler's card", "Customer service", "Ability to stand"],
    payMin: 15,
    payMax: 18,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 25,
    datePosted: daysAgo(1),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/deli-clerk-yokes",
    category: "retail",
    remote: false,
    benefits: ["Employee discount", "Flexible schedule"],
  },
  {
    id: "job-r11",
    title: "Customer Service Lead",
    company: "Home Depot",
    location: "Spokane, WA",
    description: "Supervise front-end operations, resolve customer issues, train cashiers, and ensure excellent service standards.",
    requirements: ["Retail experience", "Leadership skills", "Problem-solving", "Customer focused"],
    payMin: 19,
    payMax: 24,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 40,
    datePosted: daysAgo(3),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/cs-lead-homedepot",
    category: "retail",
    remote: false,
    benefits: ["Medical/Dental/Vision", "401k", "Stock purchase"],
  },
  {
    id: "job-r12",
    title: "Sporting Goods Associate",
    company: "Dick's Sporting Goods",
    location: "Spokane, WA",
    description: "Assist customers with sporting goods purchases, maintain department, and share product expertise.",
    requirements: ["Sports/fitness knowledge", "Retail experience", "Customer service", "Team player"],
    payMin: 15,
    payMax: 18,
    payType: "hourly",
    hoursType: "part-time",
    hoursPerWeek: 20,
    datePosted: daysAgo(0),
    source: "worksourcewa",
    sourceUrl: "https://worksourcewa.com/jobs/sporting-goods-dicks",
    category: "retail",
    remote: false,
    benefits: ["Employee discount", "Flexible hours"],
  },
  {
    id: "job-r13",
    title: "Beauty Advisor",
    company: "Ulta Beauty",
    location: "Spokane, WA",
    description: "Consult with customers on beauty products, provide makeup applications, and drive sales through product knowledge.",
    requirements: ["Beauty industry experience", "Product knowledge", "Sales skills", "Passion for beauty"],
    payMin: 16,
    payMax: 20,
    payType: "hourly",
    hoursType: "full-time",
    hoursPerWeek: 35,
    datePosted: daysAgo(4),
    source: "indeed",
    sourceUrl: "https://indeed.com/jobs/beauty-advisor-ulta",
    category: "retail",
    remote: false,
    benefits: ["Gratis products", "Employee discount", "Commission"],
  },
];

// Helper function to format pay
export function formatPay(job: Job): string {
  if (job.payType === "hourly") {
    return `$${job.payMin} - $${job.payMax}/hr`;
  }
  return `$${(job.payMin / 1000).toFixed(0)}K - $${(job.payMax / 1000).toFixed(0)}K/yr`;
}

// Helper function to format date
export function formatJobDate(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffTime = Math.abs(now.getTime() - date.getTime());
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Yesterday";
  if (diffDays < 7) return `${diffDays} days ago`;
  return date.toLocaleDateString();
}

// Get source logo/color
export function getSourceInfo(source: Job["source"]): { name: string; color: string; bgColor: string } {
  switch (source) {
    case "worksourcewa":
      return { name: "WorkSource WA", color: "#2B8A8A", bgColor: "bg-[#2B8A8A]/10" };
    case "indeed":
      return { name: "Indeed", color: "#2164f3", bgColor: "bg-blue-100" };
    case "linkedin":
      return { name: "LinkedIn", color: "#0077b5", bgColor: "bg-sky-100" };
    case "governmentjobs":
      return { name: "Government Jobs", color: "#1a365d", bgColor: "bg-indigo-100" };
    default:
      return { name: "Job Board", color: "#6b7280", bgColor: "bg-gray-100" };
  }
}
